stages:
  - install_deps
  - test
  - build
  - deploy_qa
  - deploy_prd

cache:
  paths:
    - node_modules/

install_deps:
  stage: install_deps
  script:
    - cd /home/www/cash-bus-api
    - git pull origin master
    - npm config set registry https://registry.npm.taobao.org
    - npm install

test:
  stage: test
  only:
    - develop
    - master
  script:
    - echo "Run test"

build:
  stage: build
  script:
    - npm run build

deploy_qa:
  stage: deploy_qa
  only: 
    - develop
  script:
    - echo "Deploy qa"

deploy_prd:
  stage: deploy_prd
  only: 
    - master
  script:
    - cd /home/www/cash-bus-api
    - cp src/app/logging.json build/app/logging.json
    - pm2 restart cash-bus-api-dev