cache:
  paths:
  - node_modules/

deploy_prd:
 stage: deploy
 only: 
  - master
 script:
  - cd /home/www/cash-bus-api
  - git pull origin master
  - npm config set registry https://registry.npm.taobao.org
  - npm install
  - pm2 restart cash-bus-api-dev