cache:
  paths:
  - node_modules/
   
deploy:
 stage: deploy
 script:
  - git pull origin master
  - npm config set registry https://registry.npm.taobao.org
  - npm install
  - pm2 restart cash-bus-api-dev
