cache:
  paths:
  - node_modules/

deploy_prd:
 stage: deploy_prd
 only: 
  - master
 script:
  - git remote -v
  - pwd
  - git pull origin master
  - npm config set registry https://registry.npm.taobao.org
  - npm install
  - pm2 restart cash-bus-api-dev